# DO NOT EDIT - Generated by RSF

locals {
  function_name = "${var.name_prefix}-${var.workflow_name}"
}

data "archive_file" "lambda_zip" {
  type        = "zip"
  source_dir  = "${var.source_dir}/src"
  output_path = "${path.module}/approval-workflow.zip"
}

resource "aws_lambda_function" "approval_workflow" {
  function_name    = local.function_name
  handler          = "generated.orchestrator.lambda_handler"
  runtime          = "python3.13"
  role             = aws_iam_role.lambda_exec.arn
  filename         = data.archive_file.lambda_zip.output_path
  source_code_hash = data.archive_file.lambda_zip.output_base64sha256
  timeout          = var.timeout
  memory_size      = var.memory_size

  durable_config {
    execution_timeout = var.execution_timeout
    retention_period  = var.retention_period
  }

  lifecycle {
    ignore_changes = [filename, source_code_hash]
  }
}
