# DO NOT EDIT - Generated by RSF

resource "aws_lambda_function_url" "lambda_url_trigger_url" {
  function_name      = aws_lambda_function.lambda_url_trigger.function_name
  authorization_type = "NONE"
}
