# DO NOT EDIT - Generated by RSF

output "function_arn" {
  description = "ARN of the Lambda function"
  value       = aws_lambda_function.lambda_url_trigger.arn
}

output "function_name" {
  description = "Name of the Lambda function"
  value       = aws_lambda_function.lambda_url_trigger.function_name
}

output "role_arn" {
  description = "ARN of the IAM role"
  value       = aws_iam_role.lambda_exec.arn
}

output "log_group_name" {
  description = "Name of the CloudWatch log group"
  value       = aws_cloudwatch_log_group.lambda_logs.name
}

output "function_url" {
  description = "Lambda Function URL endpoint"
  value       = aws_lambda_function_url.lambda_url_trigger_url.function_url
}
