"""CDK Python app generator for RSF workflows.

Generates a complete CDK app:
- app.py — CDK app entry point
- stack.py — Stack with L2 constructs
- cdk.json — CDK configuration
- requirements.txt — CDK Python dependencies
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from rsf.cdk.engine import render_cdk_template

GENERATED_MARKER = "# DO NOT EDIT - Generated by RSF"

# Files generated for a CDK app.
# Python files (.py) use Generation Gap pattern (skip if user-edited).
# Config files (cdk.json, requirements.txt) are always overwritten.
TEMPLATE_FILES = {
    "app.py": "app.py.j2",
    "stack.py": "stack.py.j2",
    "cdk.json": "cdk_json.j2",
    "requirements.txt": "requirements.txt.j2",
}

# Files that use Generation Gap (only .py files)
GENERATION_GAP_FILES = {"app.py", "stack.py"}


@dataclass
class CDKConfig:
    """Configuration for CDK app generation."""

    workflow_name: str
    aws_region: str = "us-east-1"
    triggers: list[dict[str, Any]] = field(default_factory=list)
    has_sqs_triggers: bool = False
    dynamodb_tables: list[dict[str, Any]] = field(default_factory=list)
    has_dynamodb_tables: bool = False
    alarms: list[dict[str, Any]] = field(default_factory=list)
    has_alarms: bool = False
    dlq_enabled: bool = False
    dlq_max_receive_count: int = 3
    dlq_queue_name: str | None = None
    lambda_url_enabled: bool = False
    lambda_url_auth_type: str = "NONE"
    timeout_seconds: int | None = None
    stage: str | None = None


@dataclass
class CDKResult:
    """Result of CDK app generation."""

    generated_files: list[Path] = field(default_factory=list)
    skipped_files: list[Path] = field(default_factory=list)


def generate_cdk(
    config: CDKConfig,
    output_dir: Path,
) -> CDKResult:
    """Generate all CDK app files for a workflow.

    Args:
        config: CDK generation configuration.
        output_dir: Directory to write CDK app files.

    Returns:
        CDKResult with paths of created/skipped files.
    """
    output_dir.mkdir(parents=True, exist_ok=True)

    resource_id = sanitize_stack_name(config.workflow_name)
    stack_class_name = "RsfStack"
    stack_id = f"rsf-{resource_id}"

    context = {
        "workflow_name": config.workflow_name,
        "resource_id": resource_id,
        "stack_class_name": stack_class_name,
        "stack_id": stack_id,
        "aws_region": config.aws_region,
        "triggers": config.triggers,
        "has_sqs_triggers": config.has_sqs_triggers,
        "dynamodb_tables": config.dynamodb_tables,
        "has_dynamodb_tables": config.has_dynamodb_tables,
        "alarms": config.alarms,
        "has_alarms": config.has_alarms,
        "dlq_enabled": config.dlq_enabled,
        "dlq_max_receive_count": config.dlq_max_receive_count,
        "dlq_queue_name": config.dlq_queue_name,
        "lambda_url_enabled": config.lambda_url_enabled,
        "lambda_url_auth_type": config.lambda_url_auth_type,
        "timeout_seconds": config.timeout_seconds,
        "stage": config.stage,
    }

    result = CDKResult()

    for filename, template_name in TEMPLATE_FILES.items():
        file_path = output_dir / filename

        # Generation Gap: only skip .py files that have been user-edited
        if filename in GENERATION_GAP_FILES and not _should_overwrite(file_path):
            result.skipped_files.append(file_path)
            continue

        content = render_cdk_template(template_name, **context)
        file_path.write_text(content, encoding="utf-8")
        result.generated_files.append(file_path)

    return result


def sanitize_stack_name(name: str) -> str:
    """Convert a workflow name to a valid CDK stack identifier.

    CDK stack IDs should be lowercase with hyphens for readability.
    Converts PascalCase, camelCase, and special characters.

    Examples:
        MyWorkflow -> my-workflow
        my_workflow -> my-workflow
        ProcessOrderV2 -> process-order-v2
    """
    # Replace underscores with hyphens
    s = name.replace("_", "-")
    # Insert hyphen before uppercase letters following lowercase/digit
    s = re.sub(r"([a-z0-9])([A-Z])", r"\1-\2", s)
    # Insert hyphen between consecutive uppercase and following lowercase
    s = re.sub(r"([A-Z]+)([A-Z][a-z])", r"\1-\2", s)
    s = s.lower()
    # Remove non-alphanumeric/hyphen characters
    s = re.sub(r"[^a-z0-9-]", "", s)
    # Collapse multiple hyphens
    s = re.sub(r"-+", "-", s)
    # Strip leading/trailing hyphens
    s = s.strip("-")
    return s


def _should_overwrite(path: Path) -> bool:
    """Return True if path doesn't exist OR first line matches the generated marker.

    Implements the Generation Gap pattern for CDK Python files.
    """
    if not path.exists():
        return True
    first_line = path.read_text(encoding="utf-8").split("\n", 1)[0]
    return first_line.strip().startswith(GENERATED_MARKER)
