"""Snapshot tests for generated orchestrator code.

Compares generated orchestrator.py for each example workflow against
committed golden files in fixtures/snapshots/. Catches code generation
regressions with readable diffs.

Usage:
    pytest tests/test_codegen/test_snapshots.py          # compare against golden files
    pytest tests/test_codegen/test_snapshots.py --update-snapshots  # regenerate golden files
"""

from __future__ import annotations

import difflib
import re
from pathlib import Path

import pytest

from rsf.codegen.generator import render_orchestrator
from rsf.codegen.state_mappers import map_states
from rsf.dsl.parser import load_definition

# Project paths
PROJECT_ROOT = Path(__file__).parent.parent.parent
EXAMPLES_DIR = PROJECT_ROOT / "examples"
SNAPSHOTS_DIR = PROJECT_ROOT / "fixtures" / "snapshots"

# All example workflows to snapshot
EXAMPLE_WORKFLOWS = [
    "order-processing",
    "data-pipeline",
    "intrinsic-showcase",
    "lambda-url-trigger",
    "approval-workflow",
    "retry-and-recovery",
]

# Lines matching these patterns are excluded from comparison (they change between runs)
VOLATILE_PATTERNS = [
    re.compile(r"^# DO NOT EDIT - Generated by RSF .* on \d{4}-\d{2}-\d{2}T"),
    re.compile(r"^# Source: .* \(SHA-256:"),
]


def normalize_generated_code(code: str) -> str:
    """Remove volatile lines (timestamp, hash) from generated code for stable comparison.

    The generated header contains two volatile lines:
    - Line 1: "# DO NOT EDIT - Generated by RSF vX.Y.Z on 2026-03-02T..."
    - Line 2: "# Source: path/to/workflow.yaml (SHA-256: abc123...)"

    These are replaced with stable placeholders.

    Args:
        code: The full generated orchestrator source code.

    Returns:
        Code with volatile lines replaced by stable placeholders.
    """
    lines = code.split("\n")
    normalized = []
    for line in lines:
        is_volatile = any(p.search(line) for p in VOLATILE_PATTERNS)
        if is_volatile:
            if "DO NOT EDIT" in line:
                normalized.append("# [GENERATED HEADER - TIMESTAMP REMOVED]")
            elif "Source:" in line:
                normalized.append("# [SOURCE HEADER - HASH REMOVED]")
            else:
                normalized.append("# [VOLATILE LINE REMOVED]")
        else:
            normalized.append(line)
    return "\n".join(normalized)


def generate_orchestrator_for_example(example_name: str) -> str:
    """Generate orchestrator code for a named example workflow.

    Args:
        example_name: Directory name under examples/ (e.g. "order-processing").

    Returns:
        The full generated orchestrator source code (normalized).
    """
    workflow_path = EXAMPLES_DIR / example_name / "workflow.yaml"
    assert workflow_path.exists(), f"Workflow not found: {workflow_path}"

    definition = load_definition(workflow_path)
    mappings = map_states(definition)
    code = render_orchestrator(
        definition=definition,
        mappings=mappings,
        dsl_path=workflow_path,
        rsf_version="0.0.0-snapshot",  # Fixed version for stable snapshots
    )
    return normalize_generated_code(code)


# ---------------------------------------------------------------------------
# Normalization self-tests
# ---------------------------------------------------------------------------


class TestNormalize:
    """Tests for the normalize_generated_code helper."""

    def test_strips_timestamp_line(self):
        code = (
            "# DO NOT EDIT - Generated by RSF v0.1.0 on 2026-03-02T08:00:00Z\n"
            "real code"
        )
        result = normalize_generated_code(code)
        assert "2026-03-02" not in result
        assert "# [GENERATED HEADER - TIMESTAMP REMOVED]" in result
        assert "real code" in result

    def test_strips_hash_line(self):
        code = (
            "# Source: workflow.yaml (SHA-256: abc123def456)\n"
            "real code"
        )
        result = normalize_generated_code(code)
        assert "abc123" not in result
        assert "# [SOURCE HEADER - HASH REMOVED]" in result
        assert "real code" in result

    def test_preserves_normal_lines(self):
        code = "import os\n\ndef main():\n    pass\n"
        result = normalize_generated_code(code)
        assert result == code

    def test_preserves_non_volatile_comments(self):
        code = "# This is a regular comment\ncode here"
        result = normalize_generated_code(code)
        assert result == code


# ---------------------------------------------------------------------------
# Snapshot tests for all 6 example workflows
# ---------------------------------------------------------------------------


@pytest.mark.parametrize("example_name", EXAMPLE_WORKFLOWS)
class TestSnapshot:
    """Parametrized snapshot tests for all example workflows."""

    def test_snapshot_matches_golden(self, example_name, request):
        """Compare generated orchestrator against golden file.

        When --update-snapshots is passed, writes the golden file instead.
        """
        update = request.config.getoption("--update-snapshots", default=False)
        golden_path = SNAPSHOTS_DIR / f"{example_name}.py.snapshot"

        generated = generate_orchestrator_for_example(example_name)

        if update:
            SNAPSHOTS_DIR.mkdir(parents=True, exist_ok=True)
            golden_path.write_text(generated, encoding="utf-8")
            pytest.skip(f"Updated golden file: {golden_path}")
            return

        if not golden_path.exists():
            pytest.fail(
                f"Golden file missing: {golden_path}\n"
                f"Run with --update-snapshots to generate:\n"
                f"  pytest tests/test_codegen/test_snapshots.py --update-snapshots"
            )

        golden = golden_path.read_text(encoding="utf-8")

        if generated != golden:
            diff = difflib.unified_diff(
                golden.splitlines(keepends=True),
                generated.splitlines(keepends=True),
                fromfile=f"golden/{example_name}.py.snapshot",
                tofile=f"generated/{example_name}",
                lineterm="",
                n=5,
            )
            diff_text = "\n".join(diff)
            pytest.fail(
                f"Snapshot mismatch for {example_name}!\n\n"
                f"Generated orchestrator differs from golden file.\n"
                f"To update: pytest tests/test_codegen/test_snapshots.py --update-snapshots\n\n"
                f"Diff:\n{diff_text}"
            )
